[Interface]
PrivateKey = [CLIENT_PRIVATE_KEY] 
Address = 10.10.0.2/32
DNS = 8.8.8.8

[Peer]
PublicKey = [SERVER_PUBLIC_KEY] 
Endpoint = [domain.example.com]:[port]
AllowedIPs = 10.10.0.1/32 # allow only one ip, wireguard tunnel server

# Alternatively to send ALL traffic through VPN tunnel use the next line and delete, or comment out, the other
# AllowedIps = 0.0.0.0/0
