[Interface]
PrivateKey = [CLIENT_PRIVATE_KEY] 
Address = 10.10.0.3/32
DNS = 8.8.8.8

[Peer]
PublicKey = [SERVER_PUBLIC_KEY] 
Endpoint = [domain.example.com]:[port]
AllowedIPs = 10.10.0.1/32 #allow only one ip, wireguard tunnel server
