# Change user and password wth you real ones
[homeserver]
127.0.0.1:2222 ansible_user=vagrant ansible_password=vagrant

# If provisioning takes place locally you can use the following lines instead
# [homeserver]
# localhost ansible_connection=local ansible_user=vagrant
