- hosts: homeserver
  become: true 
  roles:
    - basic # update system and install basic packages and stuff (e.g., python, curl...)
    - ssh # copy ssh-key, disable password login using regex
    - caddy # install caddy
    - services # copy docker services configuration files and start them
    - git-server # initiate a git server
