# this file provides a basic configuration for wireguard server
# iptables rules only accept packets inside the same machine where wireguard is hosted

[Interface]
Address = 10.10.0.1/24i # wireguard interface ip

# iptables rules when setting up the wg0 interface
PostUp = iptables -A INPUT -i eth0 -p udp --dport 51820 -j ACCEPT # accept udp on port 51820 where wireguard is listening
PostUp = iptables -A INPUT -i wg0 -j ACCEPT # accept packets from wireguard interface

# clean rules when interface is down
PostDown = iptables -D INPUT -i eth0 -p udp --dport 51820 -j ACCEPT
PostDown = iptables -D INPUT -i wg0 -j ACCEPT

ListenPort = 51820
PrivateKey = [SERVER-PRIVATE-KEY]

[Peer]
PublicKey = [PEER-PUBLIC-KEY]
AllowedIPs = 10.10.0.2/32

# you can add other peers down here
